<?php

/**
 * @file
 * The primary PHP file for a Forty Acres subtheme.
 */

/**
 * Implements hook_preprocess_field().
 */
function tec_common_theme_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'field_utexas_sl_social_links') {
    $links = $variables['items'][0]['content']['links'];
    foreach ($links as $key => $link) {
      $variables['items'][0]['content']['links'][$key]['#attributes'] = [
        'target' => '_blank',
      ];
    }
  }
}
